minecraft_version=26.2
neo_version=26.2.0.57
minecraft_version_range=[26.2]
admin_version=2.3.2
fixes_version=2.5.1
qol_version=2.3.0
hud_version=1.0.0
mod_license=MIT
mod_name=Utility Core Fixes
mod_id=utility_core_fixes
mod_version=2.3.4
mod_framework=neoforge
architectury_version=10.1.12
loom_version=2.4.15
org.gradle.jvmargs=-Xmx4g