plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'com.github.johnrengelman.shadow'
}

ext {
    mod_id = "utility_core_fixes"
    mod_name = "Utility Core Fixes"
}

neoForge {
    version = neo_version
}

dependencies {
}

jar {
    archiveBaseName = "utility_core_fixes-${minecraft_version}-neoforge-${neo_version}"
    manifest {
        attributes(
            "Mod-ID": "utility_core_fixes",
            "Mod-Name": "Utility Core Fixes",
            "Mod-Version": project.version.toString()
        )
    }
}