plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'com.github.johnrengelman.shadow'
}

ext {
    mod_id = "utility_core_admin"
    mod_name = "Utility Core Admin"
}

neoForge {
    version = neo_version
}

dependencies {
}

jar {
    archiveBaseName = "utility_core_admin"
    manifest {
        attributes(
            "Mod-ID": "utility_core_admin",
            "Mod-Name": "Utility Core Admin",
            "Mod-Version": project.version.toString()
        )
    }
}